# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exercice1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import gurobipy as gp


# CULT STRUCTURE
class Cult:
    def __init__(self, nom, R, PU, MO, HM, E, SMO, FX):
        self.nom = nom
        self.R = R
        self.PU = PU
        self.MO = MO
        self.HM = HM
        self.E = E
        self.SMO = SMO
        self.FX = FX


class PL1_Ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 619)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 90, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 90, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(380, 90, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(440, 90, 55, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(520, 90, 61, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 130, 101, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 170, 111, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 210, 101, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 250, 121, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(30, 290, 91, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 330, 131, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(30, 370, 121, 16))
        self.label_13.setObjectName("label_13")
        self.ble1 = QtWidgets.QLineEdit(self.centralwidget)
        self.ble1.setGeometry(QtCore.QRect(200, 120, 61, 22))
        self.ble1.setObjectName("ble1")
        self.orge1 = QtWidgets.QLineEdit(self.centralwidget)
        self.orge1.setGeometry(QtCore.QRect(280, 120, 61, 22))
        self.orge1.setObjectName("orge1")
        self.mais1 = QtWidgets.QLineEdit(self.centralwidget)
        self.mais1.setGeometry(QtCore.QRect(360, 120, 61, 22))
        self.mais1.setObjectName("mais1")
        self.betsucre1 = QtWidgets.QLineEdit(self.centralwidget)
        self.betsucre1.setGeometry(QtCore.QRect(440, 120, 61, 22))
        self.betsucre1.setObjectName("betsucre1")
        self.tournesol1 = QtWidgets.QLineEdit(self.centralwidget)
        self.tournesol1.setGeometry(QtCore.QRect(520, 120, 61, 22))
        self.tournesol1.setObjectName("tournesol1")
        self.ble2 = QtWidgets.QLineEdit(self.centralwidget)
        self.ble2.setGeometry(QtCore.QRect(200, 160, 61, 22))
        self.ble2.setObjectName("ble2")
        self.orge2 = QtWidgets.QLineEdit(self.centralwidget)
        self.orge2.setGeometry(QtCore.QRect(280, 160, 61, 22))
        self.orge2.setObjectName("orge2")
        self.mais2 = QtWidgets.QLineEdit(self.centralwidget)
        self.mais2.setGeometry(QtCore.QRect(360, 160, 61, 22))
        self.mais2.setObjectName("mais2")
        self.betsucre2 = QtWidgets.QLineEdit(self.centralwidget)
        self.betsucre2.setGeometry(QtCore.QRect(440, 160, 61, 22))
        self.betsucre2.setObjectName("betsucre2")
        self.tournesol2 = QtWidgets.QLineEdit(self.centralwidget)
        self.tournesol2.setGeometry(QtCore.QRect(520, 160, 61, 22))
        self.tournesol2.setObjectName("tournesol2")
        self.ble3 = QtWidgets.QLineEdit(self.centralwidget)
        self.ble3.setGeometry(QtCore.QRect(200, 200, 61, 22))
        self.ble3.setObjectName("ble3")
        self.orge3 = QtWidgets.QLineEdit(self.centralwidget)
        self.orge3.setGeometry(QtCore.QRect(280, 200, 61, 22))
        self.orge3.setObjectName("orge3")
        self.mais3 = QtWidgets.QLineEdit(self.centralwidget)
        self.mais3.setGeometry(QtCore.QRect(360, 200, 61, 22))
        self.mais3.setObjectName("mais3")
        self.betsucre3 = QtWidgets.QLineEdit(self.centralwidget)
        self.betsucre3.setGeometry(QtCore.QRect(440, 200, 61, 22))
        self.betsucre3.setObjectName("betsucre3")
        self.tournesol3 = QtWidgets.QLineEdit(self.centralwidget)
        self.tournesol3.setGeometry(QtCore.QRect(520, 200, 61, 22))
        self.tournesol3.setObjectName("tournesol3")
        self.ble4 = QtWidgets.QLineEdit(self.centralwidget)
        self.ble4.setGeometry(QtCore.QRect(200, 240, 61, 22))
        self.ble4.setObjectName("ble4")
        self.orge4 = QtWidgets.QLineEdit(self.centralwidget)
        self.orge4.setGeometry(QtCore.QRect(280, 240, 61, 22))
        self.orge4.setObjectName("orge4")
        self.mais4 = QtWidgets.QLineEdit(self.centralwidget)
        self.mais4.setGeometry(QtCore.QRect(360, 240, 61, 22))
        self.mais4.setObjectName("mais4")
        self.betsucre4 = QtWidgets.QLineEdit(self.centralwidget)
        self.betsucre4.setGeometry(QtCore.QRect(440, 240, 61, 22))
        self.betsucre4.setObjectName("betsucre4")
        self.tournesol4 = QtWidgets.QLineEdit(self.centralwidget)
        self.tournesol4.setGeometry(QtCore.QRect(520, 240, 61, 22))
        self.tournesol4.setObjectName("tournesol4")
        self.ble5 = QtWidgets.QLineEdit(self.centralwidget)
        self.ble5.setGeometry(QtCore.QRect(200, 280, 61, 22))
        self.ble5.setObjectName("ble5")
        self.orge5 = QtWidgets.QLineEdit(self.centralwidget)
        self.orge5.setGeometry(QtCore.QRect(280, 280, 61, 22))
        self.orge5.setObjectName("orge5")
        self.mais5 = QtWidgets.QLineEdit(self.centralwidget)
        self.mais5.setGeometry(QtCore.QRect(360, 280, 61, 22))
        self.mais5.setObjectName("mais5")
        self.betsucre5 = QtWidgets.QLineEdit(self.centralwidget)
        self.betsucre5.setGeometry(QtCore.QRect(440, 280, 61, 22))
        self.betsucre5.setObjectName("betsucre5")
        self.tournesol5 = QtWidgets.QLineEdit(self.centralwidget)
        self.tournesol5.setGeometry(QtCore.QRect(520, 280, 61, 22))
        self.tournesol5.setObjectName("tournesol5")
        self.ble6 = QtWidgets.QLineEdit(self.centralwidget)
        self.ble6.setGeometry(QtCore.QRect(200, 320, 61, 22))
        self.ble6.setObjectName("ble6")
        self.orge6 = QtWidgets.QLineEdit(self.centralwidget)
        self.orge6.setGeometry(QtCore.QRect(280, 320, 61, 22))
        self.orge6.setObjectName("orge6")
        self.mais6 = QtWidgets.QLineEdit(self.centralwidget)
        self.mais6.setGeometry(QtCore.QRect(360, 320, 61, 22))
        self.mais6.setObjectName("mais6")
        self.betsucre6 = QtWidgets.QLineEdit(self.centralwidget)
        self.betsucre6.setGeometry(QtCore.QRect(440, 320, 61, 22))
        self.betsucre6.setObjectName("betsucre6")
        self.tournesol6 = QtWidgets.QLineEdit(self.centralwidget)
        self.tournesol6.setGeometry(QtCore.QRect(520, 320, 61, 22))
        self.tournesol6.setObjectName("tournesol6")
        self.ble7 = QtWidgets.QLineEdit(self.centralwidget)
        self.ble7.setGeometry(QtCore.QRect(200, 360, 61, 22))
        self.ble7.setObjectName("ble7")
        self.orge7 = QtWidgets.QLineEdit(self.centralwidget)
        self.orge7.setGeometry(QtCore.QRect(280, 360, 61, 22))
        self.orge7.setObjectName("orge7")
        self.mais7 = QtWidgets.QLineEdit(self.centralwidget)
        self.mais7.setGeometry(QtCore.QRect(360, 360, 61, 22))
        self.mais7.setObjectName("mais7")
        self.betsucre7 = QtWidgets.QLineEdit(self.centralwidget)
        self.betsucre7.setGeometry(QtCore.QRect(440, 360, 61, 22))
        self.betsucre7.setObjectName("betsucre7")
        self.tournesol7 = QtWidgets.QLineEdit(self.centralwidget)
        self.tournesol7.setGeometry(QtCore.QRect(520, 360, 61, 22))
        self.tournesol7.setObjectName("tournesol7")
        self.resoudre1 = QtWidgets.QPushButton(self.centralwidget)
        self.resoudre1.setGeometry(QtCore.QRect(630, 100, 93, 461))
        self.resoudre1.setObjectName("resoudre1")
        self.resoudre1.clicked.connect(self.exercice1)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(30, 440, 161, 16))
        self.label_19.setObjectName("label_19")
        self.surface_zone = QtWidgets.QLineEdit(self.centralwidget)
        self.surface_zone.setGeometry(QtCore.QRect(200, 440, 61, 22))
        self.surface_zone.setObjectName("surface_zone")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(30, 480, 101, 16))
        self.label_17.setObjectName("label_17")
        self.main_oeuvre = QtWidgets.QLineEdit(self.centralwidget)
        self.main_oeuvre.setGeometry(QtCore.QRect(200, 480, 61, 22))
        self.main_oeuvre.setObjectName("main_oeuvre")
        self.eau_irrig = QtWidgets.QLineEdit(self.centralwidget)
        self.eau_irrig.setGeometry(QtCore.QRect(520, 440, 61, 22))
        self.eau_irrig.setObjectName("eau_irrig")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(350, 440, 161, 16))
        self.label_18.setObjectName("label_18")
        self.heures_machine = QtWidgets.QLineEdit(self.centralwidget)
        self.heures_machine.setGeometry(QtCore.QRect(520, 480, 61, 22))
        self.heures_machine.setObjectName("heures_machine")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(350, 480, 161, 16))
        self.label_16.setObjectName("label_16")
        self.prix_metre = QtWidgets.QLineEdit(self.centralwidget)
        self.prix_metre.setGeometry(QtCore.QRect(520, 520, 61, 22))
        self.prix_metre.setObjectName("prix_metre")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(30, 520, 131, 16))
        self.label_15.setObjectName("label_15")
        self.cout_heure = QtWidgets.QLineEdit(self.centralwidget)
        self.cout_heure.setGeometry(QtCore.QRect(200, 520, 61, 22))
        self.cout_heure.setObjectName("cout_heure")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(350, 520, 161, 16))
        self.label_14.setObjectName("label_14")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PL 1:"))
        self.label_2.setText(_translate("MainWindow", "Blé"))
        self.label_3.setText(_translate("MainWindow", "Orge"))
        self.label_4.setText(_translate("MainWindow", "Mais"))
        self.label_5.setText(_translate("MainWindow", "Bet-sucre"))
        self.label_6.setText(_translate("MainWindow", "Tournesol"))
        self.label_7.setText(_translate("MainWindow", "Rendement Q/ha"))
        self.label_8.setText(_translate("MainWindow", "Prix de vente UM/Q"))
        self.label_9.setText(_translate("MainWindow", "M.O ouvriers /ha"))
        self.label_10.setText(_translate("MainWindow", "Temps Machine H/ha"))
        self.label_11.setText(_translate("MainWindow", "Eau m3/ha"))
        self.label_12.setText(_translate("MainWindow", "Salaire annuel/Ouvrier"))
        self.label_13.setText(_translate("MainWindow", "Frais fixe de gestion"))
        self.resoudre1.setText(_translate("MainWindow", "Résoudre"))
        self.label_19.setText(_translate("MainWindow", "Surface de la zone agricole"))
        self.label_17.setText(_translate("MainWindow", "Main d\'oeuvre"))
        self.label_18.setText(_translate("MainWindow", "Eau d\'irrigation"))
        self.label_16.setText(_translate("MainWindow", "Heures machine"))
        self.label_15.setText(_translate("MainWindow", "Cout heure machine"))
        self.label_14.setText(_translate("MainWindow", "Prix metre cube"))

    def exercice1(self):
        PEau = float(self.prix_metre.text())
        PHM = int(self.heures_machine.text())
        surface = int(self.surface_zone.text())
        maxMO = int(self.main_oeuvre.text())
        maxEau = int(self.eau_irrig.text())
        maxHM = int(self.heures_machine.text())
        # INITIALIZATION
        Ble = Cult("Ble", int(self.ble1.text()), int(self.ble2.text()), int(self.ble3.text()),
                   int(self.ble4.text()), int(self.ble5.text()), int(self.ble6.text()), int(self.ble7.text()))
        # print(Ble.SMO)
        Orge = Cult("Orge", int(self.orge1.text()), int(self.orge2.text()), int(self.orge3.text()),
                    int(self.orge4.text()), int(self.orge5.text()), int(self.orge6.text()),
                    int(self.orge7.text()))
        Mais = Cult("Mais", int(self.mais1.text()), int(self.mais2.text()), int(self.mais3.text()),
                    int(self.mais4.text()), int(self.mais5.text()), int(self.mais6.text()),
                    int(self.mais7.text()))
        Betrave = Cult("Betrave", int(self.betsucre1.text()), int(self.betsucre2.text()),
                       int(self.betsucre3.text()), int(self.betsucre4.text()), int(self.betsucre5.text()),
                       int(self.betsucre6.text()), int(self.betsucre7.text()))
        Tournesol = Cult("Tournesol", int(self.tournesol1.text()), int(self.tournesol2.text()),
                         int(self.tournesol3.text()), int(self.tournesol4.text()), int(self.tournesol5.text()),
                         int(self.tournesol6.text()), int(self.tournesol7.text()))
        Cultures = [Ble, Orge, Mais, Betrave, Tournesol]

        # BENEF per HECT
        BenefpH = [(cult.R * cult.PU) - (cult.MO * cult.SMO + cult.HM * PHM + cult.E * PEau) for cult in Cultures]
        # print(BenefpH)
        # print()
        model = gp.Model("NationalAgriculture")
        # Test
        # DECISION VARIABLES
        xBle = model.addVar(lb=0, name="xBle")
        xOrge = model.addVar(lb=0, name="xOrge")
        xMais = model.addVar(lb=0, name="xMais")
        xBet = model.addVar(lb=0, name="xBet")
        xTour = model.addVar(lb=0, name="xTour")

        vals = [xBle, xOrge, xMais, xBet, xTour]

        yBle = model.addVar(vtype=gp.GRB.BINARY, name="yBle")
        yOrge = model.addVar(vtype=gp.GRB.BINARY, name="yOrge")
        yMais = model.addVar(vtype=gp.GRB.BINARY, name="yMais")
        yBet = model.addVar(vtype=gp.GRB.BINARY, name="yBet")
        yTour = model.addVar(vtype=gp.GRB.BINARY, name="yTour")
        # print(xTour)

        # OBJECTUVE FUNCTION
        model.setObjective((xBle * BenefpH[0] - yBle * Ble.FX) + (xOrge * BenefpH[1] - yOrge * Orge.FX) + (
                xMais * BenefpH[2] - yMais * Mais.FX) + (xBet * BenefpH[3] - yBet * Betrave.FX) + (
                                   xTour * BenefpH[4] - yTour * Tournesol.FX), gp.GRB.MAXIMIZE)

        # CONSTRAINTS
        model.addConstr(xBle + xOrge + xMais + xBet + xTour <= surface, name="GROUND CONSTRAINT")
        model.addConstr(
            (xBle * Ble.MO) + (xOrge * Orge.MO) + (xMais * Mais.MO) + (xBet * Betrave.MO) + (
                    xTour * Tournesol.MO) <= maxMO,
            name="MO CONSTRAINT")
        model.addConstr(
            xBle * Ble.E + xMais * Mais.E + xOrge * Orge.E + xBet * Betrave.E + xTour * Tournesol.E <= maxEau,
            name="Water CONSTRAINT")
        model.addConstr(
            xBle * Ble.HM + xOrge * Orge.HM + xMais * Mais.HM + xBet * Betrave.HM + xTour * Tournesol.HM <= maxHM,
            name="HM CONSTRAINT")
        model.addConstr(xBle <= yBle * 1000, name="Ble")
        model.addConstr(xOrge <= yOrge * 1000, name="Orge")
        model.addConstr(xMais <= yMais * 1000, name="Mais")
        model.addConstr(xBet <= yBet * 1000, name="Betrave")
        model.addConstr(xTour <= yTour * 1000, name="Tournesol")

        model.optimize()
        print(model.ObjVal)
        with open("Resolutions/PL1.txt", "w") as f:
            sys.stdout = f
            # print(model.status == gp.GRB.OPTIMAL)
            print(f'Valeur objective du model : {model.ObjVal}')
            i = 0
            for val in vals:
                print(f'x{i} : {val.X}')
                i += 1
if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = PL1_Ui()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())