# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exercice2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import gurobipy as gb


class PL2_Ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(778, 680)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.resoudre1 = QtWidgets.QPushButton(self.centralwidget)
        self.resoudre1.clicked.connect(self.PL2)
        self.resoudre1.setGeometry(QtCore.QRect(610, 120, 93, 421))
        self.resoudre1.setObjectName("resoudre1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 170, 171, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 210, 161, 16))
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(130, 250, 55, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(130, 290, 101, 16))
        self.label_9.setObjectName("label_9")
        self.qtype1 = QtWidgets.QLineEdit(self.centralwidget)
        self.qtype1.setGeometry(QtCore.QRect(360, 160, 113, 22))
        self.qtype1.setObjectName("qtype1")
        self.qtype2 = QtWidgets.QLineEdit(self.centralwidget)
        self.qtype2.setGeometry(QtCore.QRect(360, 200, 113, 22))
        self.qtype2.setObjectName("qtype2")
        self.gain_gaz = QtWidgets.QLineEdit(self.centralwidget)
        self.gain_gaz.setGeometry(QtCore.QRect(360, 240, 113, 22))
        self.gain_gaz.setObjectName("gain_gaz")
        self.gain_chauffage = QtWidgets.QLineEdit(self.centralwidget)
        self.gain_chauffage.setGeometry(QtCore.QRect(360, 280, 113, 22))
        self.gain_chauffage.setObjectName("gain_chauffage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 778, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PL 2:"))
        self.resoudre1.setText(_translate("MainWindow", "Résoudre"))
        self.label_2.setText(_translate("MainWindow", "Qtype1"))
        self.label_3.setText(_translate("MainWindow", "Qtype2"))
        self.label_8.setText(_translate("MainWindow", "gain Gaz"))
        self.label_9.setText(_translate("MainWindow", "gain Chauffage"))

    def PL2(self):
        Qtype1, Qtype2, gG, gC = float(self.qtype1.text()),float(self.qtype2.text()),float(self.gain_gaz.text()),float(self.gain_chauffage.text())
        PL2 = gb.Model("PL2")
        # ============================================VARIABLES
        repartition = []
        q11 = PL2.addVar(lb=0, vtype=gb.GRB.INTEGER, name='q11')
        q12 = PL2.addVar(lb=0, vtype=gb.GRB.INTEGER, name='q12')
        q21 = PL2.addVar(lb=0, vtype=gb.GRB.INTEGER, name='q21')
        q22 = PL2.addVar(lb=0, vtype=gb.GRB.INTEGER, name='q22')
        # ============================================CONSTRAINTS
        PL2.addConstr(q11 + q12 <= Qtype1, "Quantité en type 1")
        PL2.addConstr(q21 + q22 <= Qtype2, "Quantité en type 2")
        PL2.addConstr((10 * q11 + 5 * q21) >= 8 * (q11 + q21), "Contrainte de qualité Gazoline")
        PL2.addConstr((10 * q12 + 5 * q22) >= 6 * (q12 + q22), "Contrainte de qualité Gaz de Chauffage")
        # ============================================SOLVE
        Income = gG * (q11 + q21) + gC * (q12 + q22)
        PL2.setObjective(Income, gb.GRB.MAXIMIZE)
        PL2.optimize()
        vars = PL2.getVars()
        with open("Resolutions/PL2.txt", "w") as f:
            sys.stdout = f
            # print(model.status == gp.GRB.OPTIMAL)
            for var in vars:
                print(var.varName, var.x)
            print(f'Resultant en un profit de {PL2.ObjVal} Dt')



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = PL2_Ui()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
