# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exercice3.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np
import gurobipy as gp
import pandas as pd
from gurobipy import Model, GRB, quicksum

"""
minimun_req = [17,13,15,19,14,16,11]
x1,x2 = planifier(minimun_req)
print(x1)
print(x2)
"""


def init_interface_(interface):
    interface.lundi_req.setText(str(x_lundi_req))
    interface.mardi_req.setText(str(x_mardi_req))
    interface.mercredi_req.setText(str(x_mercredi_req))
    interface.jeudi_req.setText(str(x_jeudi_req))
    interface.vendredi_req.setText(str(x_vendredi_req))
    interface.samedi_req.setText(str(x_samedi_req))
    interface.dimanche_req.setText(str(x_dimanche_req))


class PL3_Ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.resoudre1 = QtWidgets.QPushButton(self.centralwidget)
        self.resoudre1.clicked.connect(self.planification)
        self.resoudre1.setGeometry(QtCore.QRect(610, 110, 93, 421))
        self.resoudre1.setObjectName("resoudre1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 140, 91, 20))
        self.label_2.setObjectName("label_2")
        self.x_lundi_req = QtWidgets.QLineEdit(self.centralwidget)
        self.x_lundi_req.setGeometry(QtCore.QRect(290, 140, 113, 22))
        self.x_lundi_req.setObjectName("x_lundi_req")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 180, 91, 20))
        self.label_3.setObjectName("label_3")
        self.x_mardi_req = QtWidgets.QLineEdit(self.centralwidget)
        self.x_mardi_req.setGeometry(QtCore.QRect(290, 180, 113, 22))
        self.x_mardi_req.setObjectName("x_mardi_req")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 220, 101, 20))
        self.label_4.setObjectName("label_4")
        self.x_mercredi_req = QtWidgets.QLineEdit(self.centralwidget)
        self.x_mercredi_req.setGeometry(QtCore.QRect(290, 220, 113, 22))
        self.x_mercredi_req.setObjectName("x_mercredi_req")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 260, 91, 20))
        self.label_5.setObjectName("label_5")
        self.x_jeudi_req = QtWidgets.QLineEdit(self.centralwidget)
        self.x_jeudi_req.setGeometry(QtCore.QRect(290, 260, 113, 22))
        self.x_jeudi_req.setObjectName("x_jeudi_req")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(100, 300, 91, 20))
        self.label_6.setObjectName("label_6")
        self.x_vendredi_req = QtWidgets.QLineEdit(self.centralwidget)
        self.x_vendredi_req.setGeometry(QtCore.QRect(290, 300, 113, 22))
        self.x_vendredi_req.setObjectName("x_vendredi_req")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(100, 340, 91, 20))
        self.label_7.setObjectName("label_7")
        self.x_samedi_req = QtWidgets.QLineEdit(self.centralwidget)
        self.x_samedi_req.setGeometry(QtCore.QRect(290, 340, 113, 22))
        self.x_samedi_req.setObjectName("x_samedi_req")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(100, 380, 91, 20))
        self.label_8.setObjectName("label_8")
        self.x_dimache_req = QtWidgets.QLineEdit(self.centralwidget)
        self.x_dimache_req.setGeometry(QtCore.QRect(290, 380, 113, 22))
        self.x_dimache_req.setObjectName("x_dimache_req")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PL 3:"))
        self.resoudre1.setText(_translate("MainWindow", "Résoudre"))
        self.label_2.setText(_translate("MainWindow", "x_lundi_req"))
        self.label_3.setText(_translate("MainWindow", "x_mardi_req"))
        self.label_4.setText(_translate("MainWindow", "x_mercredi_req"))
        self.label_5.setText(_translate("MainWindow", "x_jeudi_req"))
        self.label_6.setText(_translate("MainWindow", "x_vendredi_req"))
        self.label_7.setText(_translate("MainWindow", "x_samedi_req"))
        self.label_8.setText(_translate("MainWindow", "x_dimache_req"))

    def planification(self):
        # ===================INITILISATION
        x1, x2, x3, x4, x5, x6, x7 = int(self.x_lundi_req.text()) , int(self.x_mardi_req.text()) , \
                                     int(self.x_mercredi_req.text()) , int(self.x_jeudi_req.text()) , int(self.x_vendredi_req.text()) , \
                                     int(self.x_samedi_req.text()) , int(self.x_dimache_req.text())
        jours = [x1, x2, x3, x4, x5, x6, x7]
        jour = ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche']
        mat = np.ones((7, 7), dtype=int)
        for c in range(7):
            i = c + 5
            mat[i % 7, c] = 0
            mat[(i + 1) % 7, c] = 0

        # ===================MODEL
        PL3 = gp.Model("PL3")
        x = []
        for i in range(7):
            x.append(PL3.addVar(lb=0, vtype=gp.GRB.INTEGER, name='x' + str(i + 1)))
        X = np.array(x)
        X = X.reshape((1, 7))
        for j in range(7):
            PL3.addConstr(gp.quicksum(mat[j, :] * x) >= jours[j],
                          "Nbre d'employé min requis pour " + jour[j] + " est " + str(jours[j]))

        PL3.setObjective(gp.quicksum(x), gp.GRB.MINIMIZE)

        PL3.optimize()

        # ===================PLANIFICATION
        aux = []
        for i in range(7):
            aux.append(int(x[i].x))
        result = []
        for i in range(7):
            result.append(aux[(i + 2) % 7])
        with open("Resolutions/PL3.txt", "w") as f:
            sys.stdout = f
            sheet = {}
            print("plannification des congés ")
            for i in range(7):
                print(jour[i] + "  :" + str(result[i]))
                sheet.update({jour[i]: [result[i]]})
            df = pd.DataFrame(sheet)
            df.to_excel("Resolution_excel/pl3.xlsx", index=False)

            # ===================RESOLUTION
            print("le nombre totale optimale des employés est ", int(PL3.objVal))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = PL3_Ui()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
