# -*- coding: utf-8 -*-
import pandas as pd
# Form implementation generated from reading ui file 'exercice5.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import gurobipy as gb
import pandas as pd

class PL5_Ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.resoudre1 = QtWidgets.QPushButton(self.centralwidget)
        self.resoudre1.clicked.connect(self.PL5)
        self.resoudre1.setGeometry(QtCore.QRect(650, 60, 93, 421))
        self.resoudre1.setObjectName("resoudre1")
        self.offre1 = QtWidgets.QLineEdit(self.centralwidget)
        self.offre1.setGeometry(QtCore.QRect(140, 110, 91, 22))
        self.offre1.setObjectName("offre1")
        self.offre2 = QtWidgets.QLineEdit(self.centralwidget)
        self.offre2.setGeometry(QtCore.QRect(250, 110, 91, 22))
        self.offre2.setObjectName("offre2")
        self.offre3 = QtWidgets.QLineEdit(self.centralwidget)
        self.offre3.setGeometry(QtCore.QRect(360, 110, 91, 22))
        self.offre3.setObjectName("offre3")
        self.demande2 = QtWidgets.QLineEdit(self.centralwidget)
        self.demande2.setGeometry(QtCore.QRect(250, 170, 91, 22))
        self.demande2.setObjectName("demande2")
        self.demnade1 = QtWidgets.QLineEdit(self.centralwidget)
        self.demnade1.setGeometry(QtCore.QRect(140, 170, 91, 22))
        self.demnade1.setObjectName("demnade1")
        self.demande3 = QtWidgets.QLineEdit(self.centralwidget)
        self.demande3.setGeometry(QtCore.QRect(360, 170, 91, 22))
        self.demande3.setObjectName("demande3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 170, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.demande4 = QtWidgets.QLineEdit(self.centralwidget)
        self.demande4.setGeometry(QtCore.QRect(480, 170, 91, 22))
        self.demande4.setObjectName("demande4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PL 5:"))
        self.label_2.setText(_translate("MainWindow", "Offre"))
        self.resoudre1.setText(_translate("MainWindow", "Résoudre"))
        self.label_3.setText(_translate("MainWindow", "Demande"))

    def PL5(self):
        Offre = [int(self.offre1.text()), int(self.offre2.text()), int(self.offre3.text()) ]
        Demande = [int(self.demnade1.text()), int(self.demande2.text()), int(self.demande3.text()), int(self.demande4.text())]

        Couts = [[8, 6, 10, 9],
                 [9, 12, 13, 7],
                 [14, 9, 16, 5]]

        PL5 = gb.Model("PL5")
        Q = [[PL5.addVar(vtype=gb.GRB.CONTINUOUS, name='q' + str(i + 1) + str(j + 1)) for i in range(4)] for j in
             range(3)]

        for i in range(4):
            PL5.addConstr(sum(Q[j][i] for j in range(3)) >= Demande[i])

        for j in range(3):
            PL5.addConstr(sum(Q[j][i] for i in range(4)) <= Offre[j])

        Cout = sum(Q[i][j] * Couts[i][j] * (10 ** 6) for i in range(3) for j in range(4))
        PL5.setObjective(Cout, gb.GRB.MINIMIZE)

        PL5.optimize()
        vars = PL5.getVars()
        sheet = {}
        with open("Resolutions/PL5.txt", "w") as f:
            sys.stdout = f
            # print(model.status == gp.GRB.OPTIMAL)
            for var in vars:
                print(var.varName, var.x)
                sheet.update({var.varName: [var.x]})
            print(f'Avec un cout minimale de {int(PL5.ObjVal)}')
            df = pd.DataFrame(sheet)
            df.to_excel("Resolution_excel/pl5.xlsx", index=False)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = PL5_Ui()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
