# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exercice9.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import gurobipy as gp
from gurobipy import GRB
import numpy as np
import pandas as pd

class PL9_Ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 121, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(160, 100, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 100, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(420, 100, 113, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(550, 100, 113, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(680, 100, 113, 22))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(420, 140, 113, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(680, 140, 113, 22))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(290, 140, 113, 22))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(550, 140, 113, 22))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 121, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(160, 140, 113, 22))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(610, 180, 181, 22))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(160, 180, 171, 22))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 180, 121, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_14.setGeometry(QtCore.QRect(370, 180, 191, 22))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_28.setGeometry(QtCore.QRect(230, 340, 41, 22))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(180, 280, 41, 22))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_18.setGeometry(QtCore.QRect(180, 310, 41, 22))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_36.setGeometry(QtCore.QRect(230, 370, 41, 22))
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_17.setGeometry(QtCore.QRect(280, 310, 41, 22))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_15.setGeometry(QtCore.QRect(280, 250, 41, 22))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_16.setGeometry(QtCore.QRect(230, 250, 41, 22))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_19.setGeometry(QtCore.QRect(230, 280, 41, 22))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_26.setGeometry(QtCore.QRect(180, 340, 41, 22))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_20.setGeometry(QtCore.QRect(180, 250, 41, 22))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_21.setGeometry(QtCore.QRect(230, 310, 41, 22))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_33.setGeometry(QtCore.QRect(280, 370, 41, 22))
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_22.setGeometry(QtCore.QRect(280, 280, 41, 22))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_34.setGeometry(QtCore.QRect(180, 370, 41, 22))
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_25.setGeometry(QtCore.QRect(280, 340, 41, 22))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 230, 151, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_29.setGeometry(QtCore.QRect(520, 250, 41, 22))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_37.setGeometry(QtCore.QRect(520, 280, 41, 22))
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_32.setGeometry(QtCore.QRect(620, 250, 41, 22))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit_48 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_48.setGeometry(QtCore.QRect(620, 310, 41, 22))
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_27.setGeometry(QtCore.QRect(470, 250, 41, 22))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_40.setGeometry(QtCore.QRect(620, 280, 41, 22))
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_35.setGeometry(QtCore.QRect(570, 280, 41, 22))
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_42.setGeometry(QtCore.QRect(470, 310, 41, 22))
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_38.setGeometry(QtCore.QRect(470, 280, 41, 22))
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_30.setGeometry(QtCore.QRect(570, 250, 41, 22))
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_41.setGeometry(QtCore.QRect(570, 310, 41, 22))
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.lineEdit_44 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_44.setGeometry(QtCore.QRect(520, 310, 41, 22))
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(390, 230, 151, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_23.setGeometry(QtCore.QRect(420, 430, 113, 22))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_24.setGeometry(QtCore.QRect(290, 430, 113, 22))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 430, 121, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_31.setGeometry(QtCore.QRect(160, 430, 113, 22))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.resoudre1 = QtWidgets.QPushButton(self.centralwidget)
        self.resoudre1.clicked.connect(self.pl9)
        self.resoudre1.setGeometry(QtCore.QRect(700, 210, 93, 291))
        self.resoudre1.setObjectName("resoudre1")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_39.setGeometry(QtCore.QRect(550, 430, 113, 22))
        self.lineEdit_39.setObjectName("lineEdit_39")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PL 9:"))
        self.label_2.setText(_translate("MainWindow", "Capacité production"))
        self.label_3.setText(_translate("MainWindow", "Cout fixe des usines"))
        self.label_4.setText(_translate("MainWindow", "Cout fixe dépot"))
        self.label_5.setText(_translate("MainWindow", "Cout production transport"))
        self.label_6.setText(_translate("MainWindow", "Couts transport clients"))
        self.label_7.setText(_translate("MainWindow", "demandes clients "))
        self.resoudre1.setText(_translate("MainWindow", "Résoudre"))

    def pl9(self):
        usines = range(5)
        depots = range(3)
        clients = range(4)

        capacites_production = [int(self.lineEdit.text()), int(self.lineEdit_2.text()), int(self.lineEdit_3.text()),
                                int(self.lineEdit_4.text()), int(self.lineEdit_5.text())]
        couts_fixes_usines = [int(self.lineEdit_10.text()), int(self.lineEdit_8.text()), int(self.lineEdit_6.text()),
                              int(self.lineEdit_9.text()), int(self.lineEdit_7.text())]
        couts_fixes_depots = [int(self.lineEdit_12.text()), int(self.lineEdit_14.text()), int(self.lineEdit_11.text())]
        couts_production_transport = [
            [int(self.lineEdit_20.text()), int(self.lineEdit_16.text()), int(self.lineEdit_15.text())],
            [int(self.lineEdit_13.text()), int(self.lineEdit_19.text()), int(self.lineEdit_22.text())],
            [int(self.lineEdit_18.text()), int(self.lineEdit_21.text()), int(self.lineEdit_17.text())],
            [int(self.lineEdit_26.text()), int(self.lineEdit_28.text()), int(self.lineEdit_25.text())],
            [int(self.lineEdit_34.text()), int(self.lineEdit_36.text()), int(self.lineEdit_33.text())]]
        couts_transport_clients = [
            [int(self.lineEdit_27.text()), int(self.lineEdit_29.text()), int(self.lineEdit_30.text()),
             int(self.lineEdit_32.text())],
            [int(self.lineEdit_38.text()), int(self.lineEdit_37.text()), int(self.lineEdit_35.text()),
             int(self.lineEdit_40.text())], [80, 30, 50, 60]]
        demandes_clients = [int(self.lineEdit_31.text()), int(self.lineEdit_24.text()), int(self.lineEdit_23.text()),
                            int(self.lineEdit_39.text())]

        # Création du modèle
        m = gp.Model()

        # Déclaration des variables de décision
        x = {}
        y = {}
        for i in usines:
            for j in depots:
                x[i, j] = m.addVar(vtype=GRB.INTEGER, lb=0, ub=capacites_production[i], name=f"x_{i}_{j}")
        for j in depots:
            for k in clients:
                y[j, k] = m.addVar(vtype=GRB.INTEGER, lb=0, ub=demandes_clients[k], name=f"y_{j}_{k}")

        # Déclaration des variables binaires pour les états des usines et des dépôts
        usine_etat = {}
        depot_etat = {}
        for i in usines:
            usine_etat[i] = m.addVar(vtype=GRB.BINARY, name=f"usine_{i}")
        for j in depots:
            depot_etat[j] = m.addVar(vtype=GRB.BINARY, name=f"depot_{j}")

        # Mise à jour du modèle pour intégrer les variables de décision
        m.update()

        # Définition de la fonction objectif
        m.setObjective(
            gp.quicksum((x[i, j] * couts_production_transport[i][j]) * usine_etat[i] for i in usines for j in depots)
            + gp.quicksum((y[j, k] * couts_transport_clients[j][k]) for j in depots for k in clients)
            + gp.quicksum(couts_fixes_usines[i] * usine_etat[i] for i in usines)
            + gp.quicksum(couts_fixes_depots[j] * depot_etat[j] for j in depots),
            GRB.MINIMIZE)

        # Ajout des contraintes
        for i in usines:
            for j in depots:
                m.addConstr(x[i, j] <= capacites_production[i] * usine_etat[i], name=f"capacite_production_{i}_{j}")
        for k in clients:
            m.addConstr(gp.quicksum(y[j, k] for j in depots) == demandes_clients[k])
        for j in range(3):
            m.addConstr(gp.quicksum(x[i, j] for i in range(5)) >= gp.quicksum(y[j, k] for k in range(4)))
        for j in range(3):
            m.addConstr(gp.quicksum(x[i, j] for i in range(5)) <= 900 * depot_etat[j])
        m.optimize()
        with open("Resolutions/PL9.txt", "w") as f:
            sys.stdout = f
            sheet = {}
            # Affichage de la solution
            if m.status == gp.GRB.OPTIMAL:
                print('Solution optimale :')
                l = np.array([[]])

                for i in range(5):
                    for j in range(3):
                        print(f'X[{i + 1},{j + 1}] = {x[i, j].x:.2f} tonnes')
                        sheet.update({
                            "x"+str(i+1)+str(j+1): [x[i, j].x]
                        })
                for j in range(3):
                    for k in range(4):
                        print(f'Y[{j + 1},{k + 1}] = {y[j][k].x:.2f} tonnes')
                        sheet.update({
                            "y" + str(j+1) + str(k+1): [y[i][j].x]
                        })
            else:
                print('Aucune solution trouvée')
            df = pd.DataFrame(sheet)
            df.to_excel("Resolution_excel/pl9.xlsx" , index=False)

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = PL9_Ui()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
